### ISSUE TITLE
Compiled gsc wont inject in 7.02

### ISSUE THREAD

**Issue by ignaciogonzalez8888** [DizzRL/ps4-bo3-gsc-injector#8]
Gives unhandled exception error every time I try to inject the compiled gsc file in 7.02. and in the app the version says 7.05 maybe that's the problem?

**Comment by someguythatmods** [comment]
@ignaciogonzalez8888 can you attach a screenshot of the error?

**Comment by ignaciogonzalez8888** [comment]
By the way everything else works, it connects, launches the payload and it attaches to bo3 and then when Im in the lobby I inject the compiled gscc and then this error shows up. If i press continue so the application wont close and I load into the game the menu doesn't show up at all.






![error](https://user-images.githubusercontent.com/87746943/140637929-8878139f-5285-4a45-a5fd-370c324cb2e8.png)



Here's what it says in the details of the error:




See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at libdebug.PS4DBG.ReceiveData(Int32 length) in C:\Users\Dizz\Documents\PS4 Modding\BO3\GSC Stuff\PS4\Projects\PS3 BO3 GSC\PS4 BO3 GSC\libdebug\PS4DBG.cs:line 323
   at libdebug.PS4DBG.AllocateMemory(Int32 pid, Int32 length) in C:\Users\Dizz\Documents\PS4 Modding\BO3\GSC Stuff\PS4\Projects\PS3 BO3 GSC\PS4 BO3 GSC\libdebug\PS4DBG.Proc.cs:line 799
   at PS4_BO3_GSC.MainWindow.injectGscButton_Click(Object sender, EventArgs e) in C:\Users\Dizz\Documents\PS4 Modding\BO3\GSC Stuff\PS4\Projects\PS3 BO3 GSC\PS4 BO3 GSC\MainWindow.cs:line 330
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
PS4 BO3 GSC
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///F:/Gaming%20Console%20Mods/PS4/Mod%20Menus%20and%20Trainers/Call%20of%20Duty%20Black%20Ops%203/PS4.BO3.GSC.v1.1.0/PS4%20BO3%20GSC.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
MetroFramework
    Assembly Version: 1.4.0.0
    Win32 Version: 1.4.0.0
    CodeBase: file:///F:/Gaming%20Console%20Mods/PS4/Mod%20Menus%20and%20Trainers/Call%20of%20Duty%20Black%20Ops%203/PS4.BO3.GSC.v1.1.0/MetroFramework.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4460.0 built by: NET48REL1LAST_W
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
MetroFramework.Fonts
    Assembly Version: 1.4.0.0
    Win32 Version: 1.4.0.0
    CodeBase: file:///F:/Gaming%20Console%20Mods/PS4/Mod%20Menus%20and%20Trainers/Call%20of%20Duty%20Black%20Ops%203/PS4.BO3.GSC.v1.1.0/MetroFramework.Fonts.DLL
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///F:/Gaming%20Console%20Mods/PS4/Mod%20Menus%20and%20Trainers/Call%20of%20Duty%20Black%20Ops%203/PS4.BO3.GSC.v1.1.0/System.Memory.DLL
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.4.1
    Win32 Version: 4.6.28619.01
    CodeBase: file:///F:/Gaming%20Console%20Mods/PS4/Mod%20Menus%20and%20Trainers/Call%20of%20Duty%20Black%20Ops%203/PS4.BO3.GSC.v1.1.0/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
Irony
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0
    CodeBase: file:///F:/Gaming%20Console%20Mods/PS4/Mod%20Menus%20and%20Trainers/Call%20of%20Duty%20Black%20Ops%203/PS4.BO3.GSC.v1.1.0/Irony.DLL
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4161.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4460.0 built by: NET48REL1LAST_W
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by someguythatmods** [comment]
Compile with my tool, then inject with PS4 Toolbox
